media:
  input: content/images
  output: ../images
  rename: random

content:
  - name: blog
    label: Blog
    path: content/blog
    format: yaml-frontmatter
    type: collection
    extension: md

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: string
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: tags
        label: Tags
        type: string
        list: true

      - name: cover
        label: Cover Image
        type: image
        required: false

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: body
        label: Body
        type: rich-text